### ISSUE TITLE
verification

### ISSUE THREAD

**Issue by hindlepert** [RSRBX07/east-ice-field-game#43]
mettre en place des vérifications afin de s'assurer que les règles du jeu sont bien respectées

**Comment by elkhalilruby** [comment]
- [ ] refuser d avancer le corbeau, si le dé n'affiche pas le corbeau
- [ ] refuser de récolter un fruit, si le dé affiche le corbeau
- [ ] refuser de récolter deux fruits de suite, sans tirer le dé
- [ ] refuser de récolter un fruit qui n est pas du couleur de dé
- [ ] refuser d'avancer le corbeau deux fois de suite

**Comment by hindlepert** [comment]
validée!!!!
